application:
  name: fitco

server:
  forward-headers-strategy: framework
  port: ${SERVER_PORT:8080}

datasource:
  url: ${PG_URL:jdbc:postgresql://localhost:5432/postgres}
  username: ${PG_USERNAME:postgres}
  password: ${PG_PASSWORD:1234}

jpa:
   properties:
     hibernate:
       dialect: org.hibernate.dialect.PostgreSQLDialect
       show_sql: true
